spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  aws:
    s3:
      bucket-name: ${AWS_S3_BUCKET_NAME}
      region: ${AWS_REGION}
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID}
      pubsub:
        subscriber:
          subscriptions:
            time-record-approval-subscription:
              topic: ${GCP_PUBSUB_TOPIC_NAME}
              auto-create: false
            password-reset-subscription:
              topic: ${PASSWORD_RESET_TOPIC}
              auto-create: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}

gcp:
  storage:
    bucket-name: ${GCP_STORAGE_BUCKET_NAME}

# --- NOVA SEÇÃO PARA FRONTENDS ---
frontend:
  # Lista de todas as URLs de frontend permitidas para CORS
  allowed-origins:
    - ${FRONTEND_BASE_URL_PLATAFORM}
    - ${FRONTEND_BASE_URL_RECORD}
    - ${FRONTEND_BASE_URL_RENDER}
  # URL padrão para usar como fallback
  default-base-url: ${FRONTEND_BASE_URL_PLATAFORM}

logging:
  pattern:
    console: "${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}"
  level:
    org.springframework:
      security: INFO