spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: localhost
    port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: secret

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
jwt:
  secret: G45B1pM7W3H2YbVx8lZqD3YcR9sXf+Ab7K0nT4zFaUQ=
  expiration: 3600000         # 1 hora em milissegundos
  refreshExpiration: 86400000 # 24 horas em milissegundos