spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:kronos_dev}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

jwt:
  secret: ${JWT_SECRET:dev-secret-change-me}

frontend:
  base-url-plataform: ${FRONTEND_BASE_URL_PLATAFORM:http://localhost:3000}
  base-url-record: ${FRONTEND_BASE_URL_RECORD:http://localhost:3001}
  base-url-local: ${FRONTEND_BASE_URL_LOCAL:http://localhost:5173}
  base-url-local-2: ${FRONTEND_BASE_URL_LOCAL_2:http://127.0.0.1:5173}

aws:
  region: ${AWS_REGION:us-east-1}
  access-key-id: ${AWS_ACCESS_KEY_ID:local-access-key}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:local-secret-key}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME:kronos-local}
    bucket-name-doc: ${AWS_S3_BUCKET_NAME_DOCS:kronos-docs-local}
  rekognition:
    collection-id: ${AWS_REKOGNITION_COLLECTION_ID:kronos-local}

kronos:
  security:
    certificate:
      path: ${KTS_CERTIFICATE_PATH:certs/dev-certificate.pfx}
      password: ${KTS_CERTIFICATE_PASSWORD:dev-certificate-password}
    biometric-term-salt: ${SECRET_TERM:dev-term-salt}
