spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.type_uuid_char: true

  redis:
    host: localhost
    port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: secret
    amqp:
      deserialization:
        trust-all: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
logging:
  pattern:
    console: "${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}"
  level:
    org.springframework:
      security: TRACE

jwt:
  secret: "dGhpc19pcy1qd3Rfc2VjcmV0X3dpdGhfMzJfYnl0ZXNfISEhISEhISE="
  expiration: 3600000
