package com.kts.kronos.domain.model.enuns;

public enum AuditAction {
    BIOMETRIC_CONSENT_ACCEPTED,
    BIOMETRIC_CONSENT_REVOKED,
    BIOMETRIC_FACE_DELETED,
    BIOMETRIC_TEMPLATE_DELETED,
    DOCUMENT_UPLOADED,
    DOCUMENT_DOWNLOADED,
    DOCUMENT_DELETED,
    LGPD_REQUEST_CREATED,
    LGPD_DATA_EXPORTED,
    LGPD_DATA_ANONYMIZED,
    SECURITY_INCIDENT_CREATED,
    SECURITY_INCIDENT_UPDATED,
    AUTH_LOGIN_SUCCESS,
    AUTH_LOGIN_FAILURE,
    AUTH_FACE_LOGIN_SUCCESS,
    AUTH_FACE_LOGIN_FAILURE,
    AUTH_PASSWORD_CHANGED,
    AUTH_PASSWORD_RESET,
    USER_CREATED,
    USER_UPDATED,
    USER_DEACTIVATED,
    USER_ACTIVATION_TOGGLED
}
