package com.kts.kronos.domain.model.enuns;

public enum AuditAction {
    BIOMETRIC_CONSENT_ACCEPTED,
    BIOMETRIC_CONSENT_REVOKED,
    BIOMETRIC_FACE_DELETED,
    BIOMETRIC_TEMPLATE_DELETED,
    DOCUMENT_UPLOADED,
    DOCUMENT_DOWNLOADED,
    DOCUMENT_DELETED,
    LGPD_REQUEST_CREATED,
    LGPD_DATA_EXPORTED,
    LGPD_DATA_ANONYMIZED,
    SECURITY_INCIDENT_CREATED,
    SECURITY_INCIDENT_UPDATED
}
