package com.kts.kronos.domain.model.enuns;

public enum LgpdRequestType {
    CONFIRM_PROCESSING,
    ACCESS,
    CORRECTION,
    ANONYMIZATION,
    BLOCKING,
    DELETION,
    PORTABILITY,
    CONSENT_REVOCATION,
    SHARING_INFORMATION,
    CONSENT_INFORMATION,
    OPPOSITION,
    AUTOMATED_DECISION_REVIEW
}
