package com.kts.kronos.domain.model.enuns;

public enum RetentionPolicyCode {
    RETENTION_BIOMETRIC_ACTIVE_CONSENT,
    RETENTION_BIOMETRIC_EVIDENCE,
    RETENTION_TIME_RECORD,
    RETENTION_EMPLOYEE_CONTRACT,
    RETENTION_DOCUMENT_GENERAL,
    RETENTION_DOCUMENT_LABOR,
    RETENTION_SECURITY_LOG,
    RETENTION_LGPD_REQUEST,
    RETENTION_INTERNAL_MESSAGE,
    RETENTION_PASSWORD_RESET_TOKEN
}
