CREATE TABLE tb_company (
    company_id UUID PRIMARY KEY,
    name_company VARCHAR(50) NOT NULL,
    company_cnpj VARCHAR(17) NOT NULL,
    company_email VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    street VARCHAR(255),
    number VARCHAR(20),
    postal_code VARCHAR(20) NOT NULL,
    city VARCHAR(100),
    state VARCHAR(100),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION
);

CREATE TABLE tb_employee (
    employee_id UUID PRIMARY KEY,
    full_name VARCHAR(200) NOT NULL,
    cpf VARCHAR(14) NOT NULL,
    pis VARCHAR(14),
    job_position VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    salary DOUBLE PRECISION NOT NULL,
    phone VARCHAR(15),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_seen_message_timestamp TIMESTAMP,
    is_home_office BOOLEAN NOT NULL DEFAULT FALSE,
    face_s3_object_key VARCHAR(512),
    street VARCHAR(255),
    number VARCHAR(20),
    postal_code VARCHAR(20) NOT NULL,
    city VARCHAR(100),
    state VARCHAR(100),
    company_id UUID NOT NULL,
    work_start_time TIME,
    work_end_time TIME,
    break_start_time TIME,
    break_end_time TIME,
    schedule_type VARCHAR(255),
    scale_start_date DATE,
    preferred_day_off VARCHAR(255),
    weekend_off_index INTEGER,
    fixed_work_days VARCHAR(255)
);

CREATE TABLE tb_user (
    user_id UUID PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(200) NOT NULL,
    role VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    employee_id UUID
);

CREATE TABLE tb_document (
    document_id UUID PRIMARY KEY,
    employee_id UUID NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    time_record_id BIGINT,
    storage_path VARCHAR(512) NOT NULL,
    uploaded_at TIMESTAMP NOT NULL,
    document_type VARCHAR(255) NOT NULL,
    deleted_by_employee BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_by_manager BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE tb_time_records (
    time_record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_work TIMESTAMP,
    end_work TIMESTAMP,
    original_start_work TIMESTAMP,
    original_end_work TIMESTAMP,
    status_record VARCHAR(50),
    is_edite BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    employee_id UUID NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    end_latitude DOUBLE PRECISION,
    end_longitude DOUBLE PRECISION,
    nsr_checkin BIGINT,
    nsr_checkout BIGINT
);

CREATE TABLE tb_time_record_approval (
    time_record_id BIGINT PRIMARY KEY,
    requesting_employee_id UUID NOT NULL,
    manager_id UUID NOT NULL,
    new_start_work TIMESTAMP NOT NULL,
    new_end_work TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE tb_afd_entry (
    afd_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nsr BIGINT NOT NULL,
    record_type VARCHAR(1) NOT NULL,
    record_date TIMESTAMP NOT NULL,
    employee_cpf VARCHAR(11) NOT NULL,
    employee_pis VARCHAR(11),
    company_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    previous_hash VARCHAR(64),
    current_hash VARCHAR(64) NOT NULL
);

CREATE TABLE tb_company_nsr (
    company_id UUID PRIMARY KEY,
    last_nsr BIGINT
);

CREATE TABLE tb_password_reset_token (
    token VARCHAR(64) PRIMARY KEY,
    user_id UUID NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE tb_blacklisted_token (
    token_hash VARCHAR(255) PRIMARY KEY,
    expires_at TIMESTAMP
);

CREATE TABLE tb_audit_logs (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL,
    action VARCHAR(255) NOT NULL,
    ip_address VARCHAR(255),
    user_agent VARCHAR(255),
    details TEXT,
    timestamp TIMESTAMP NOT NULL
);

CREATE TABLE tb_message (
    message_id UUID PRIMARY KEY,
    employee_id UUID NOT NULL,
    company_id UUID NOT NULL,
    title VARCHAR(256) NOT NULL,
    message_text VARCHAR(1024) NOT NULL,
    priority VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    recipient_employee_id UUID
);
